CREATE TABLE IF NOT EXISTS `__PREFIX__electronics_express` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '物流公司id',
  `express_name` varchar(255) NOT NULL DEFAULT '' COMMENT '物流公司名称',
  `express_code` varchar(30) NOT NULL DEFAULT '' COMMENT '物流公司代码 (快递100)',
  `express_code1` varchar(30) NOT NULL DEFAULT '' COMMENT '物流公司代码 (快递鸟)',
  `sort` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '排序 (数字越小越靠前)',
  `name` varchar(30) NOT NULL DEFAULT '' COMMENT '发货人姓名',
  `phone` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
  `province_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '所在省份id',
  `city_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '所在城市id',
  `region_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '所在区id',
  `detail` varchar(255) NOT NULL DEFAULT '' COMMENT '详细地址',
  `pay_type` tinyint(4) NOT NULL DEFAULT '1' COMMENT '邮费支付方式:1-现付，2-到付，3-月结，4-第三方支付(仅SF支持)',
  `create_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  `customer_name` varchar(100) DEFAULT '' COMMENT '面单客户账号',
  `customer_pwd` varchar(100) DEFAULT '' COMMENT '面单密码',
  `month_code` varchar(100) DEFAULT '' COMMENT '月结号',
  `send_site` varchar(100) DEFAULT '' COMMENT '网点编码',
  `send_staff` varchar(100) DEFAULT '' COMMENT '网点名称',
  PRIMARY KEY (`id`),
  KEY `express_code` (`express_code`),
  KEY `express_code1` (`express_code1`)
) ENGINE=InnoDB AUTO_INCREMENT=10021 DEFAULT CHARSET=utf8 COMMENT='物流公司记录表';

